[build]
  command = "yarn build"
  publish = "build/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "1; mode=block"
[[headers]]
  for = "/"
  [headers.values]
    cache-control = "public,max-age=60"
[[headers]]
  for = "/manifest.json"
  [headers.values]
    cache-control = "public,max-age=60"
[[headers]]
  for = "*.webp"
  [headers.values]
    cache-control = "public,max-age=600"
[[headers]]
  for = "*.png"
  [headers.values]
    cache-control = "public,max-age=600"
[[headers]]
  for = "*.svg"
  [headers.values]
    cache-control = "public,max-age=600"
[[headers]]
  for = "/_app/assets/*"
  [headers.values]
    cache-control = "public,max-age=31536000"
